"use client";
import { useEffect, useState } from "react";
const labels: Record<string,string> = { PRODUCTION_ORDER:"生产工单", STOCK_REPLENISHMENT:"备货", MONTHLY_PRODUCTION_PLAN:"月度生产计划", MANUAL:"手工采购" };
export default function PurchaseDemandsPage() {
  const [items,setItems]=useState<any[]>([]); const [materials,setMaterials]=useState<any[]>([]); const [error,setError]=useState("");
  const [form,setForm]=useState({materialId:"",quantity:"",needByDate:"",stockPurpose:"",replenishmentReason:"安全库存补充"});
  const load=async()=>{const [a,b]=await Promise.all([fetch("/api/erp/purchase-demands"),fetch("/api/erp/materials")]);setItems(await a.json());setMaterials(await b.json());}; useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  const create=async()=>{setError("");const r=await fetch("/api/erp/purchase-demands",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,sourceType:"STOCK_REPLENISHMENT"})});const d=await r.json();if(!r.ok)return setError(d.error||"保存失败");setForm({...form,quantity:"",stockPurpose:""});await load();};
  return <div className="space-y-5"><div><h1 className="text-2xl font-semibold">采购需求</h1><p className="text-sm text-gray-500">生产工单、月度计划、备货和手工需求统一汇总；这里只生成草稿，不会自动下采购订单。</p></div>
    <section className="rounded-xl border bg-white p-4"><h2 className="font-medium">新增备货需求</h2><div className="mt-3 grid gap-3 md:grid-cols-5"><select className="rounded border p-2 text-sm" value={form.materialId} onChange={e=>setForm({...form,materialId:e.target.value})}><option value="">选择物料</option>{materials.map(m=><option key={m.id} value={m.id}>{m.code} {m.name}</option>)}</select><input className="rounded border p-2 text-sm" type="number" min="0.01" placeholder="备货数量" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><input className="rounded border p-2 text-sm" type="date" value={form.needByDate} onChange={e=>setForm({...form,needByDate:e.target.value})}/><input className="rounded border p-2 text-sm" placeholder="备货用途" value={form.stockPurpose} onChange={e=>setForm({...form,stockPurpose:e.target.value})}/><select className="rounded border p-2 text-sm" value={form.replenishmentReason} onChange={e=>setForm({...form,replenishmentReason:e.target.value})}>{["安全库存补充","常用物料备货","长周期物料提前采购","价格上涨前备货","供应商停产风险","售后备件","临时备货","其他"].map(v=><option key={v}>{v}</option>)}</select></div><button onClick={create} className="mt-3 rounded bg-gray-900 px-4 py-2 text-sm text-white">保存备货草稿</button>{error&&<p className="mt-2 text-sm text-red-600">{error}</p>}</section>
    <section className="overflow-auto rounded-xl border bg-white"><table className="w-full min-w-[960px] text-sm"><thead className="bg-gray-50 text-left text-gray-500"><tr><th className="p-3">需求号</th><th>来源</th><th>物料</th><th>新增需求</th><th>建议采购</th><th>需要日期</th><th>状态</th><th>用途/原因</th></tr></thead><tbody>{items.map(i=><tr className="border-t" key={i.id}><td className="p-3">{i.demandNo}</td><td>{labels[i.sourceType]}</td><td>{i.material?.code} {i.material?.name}</td><td>{Number(i.requestedQuantity)} {i.material?.unit}</td><td>{Number(i.suggestedQuantity)}</td><td>{String(i.needByDate).slice(0,10)}</td><td>{i.status}</td><td>{i.stockPurpose||i.replenishmentReason||"—"}</td></tr>)}</tbody></table></section></div>;
}
