"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Boxes, ClipboardCheck, RefreshCw, ShoppingCart } from "lucide-react";

function number(value: any) { return Number(value || 0).toLocaleString("zh-CN"); }
function Section({ title, children, error }: { title: string; children: React.ReactNode; error?: string }) { return <section className="rounded-xl border bg-white p-5"><h2 className="mb-4 text-sm font-semibold text-gray-900">{title}</h2>{error ? <p className="text-sm text-amber-700">{error}</p> : children}</section>; }
function Card({ label, value, href, icon: Icon }: { label: string; value: any; href: string; icon: any }) { return <Link href={href} className="rounded-xl border bg-white p-4 transition hover:border-gray-300 hover:shadow-sm"><div className="flex gap-3"><div className="rounded-lg bg-slate-100 p-2 text-slate-700"><Icon className="h-4 w-4" /></div><div><p className="text-2xl font-semibold">{number(value)}</p><p className="text-xs text-gray-500">{label}</p></div></div></Link>; }

export default function ErpDashboardPage() {
  const [data, setData] = useState<any>(); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/erp/dashboard", { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "ERP工作台加载失败"); setData(body); } catch (reason) { setError(reason instanceof Error ? reason.message : "ERP工作台加载失败"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading && !data) return <p className="py-16 text-center text-sm text-gray-500">正在加载 ERP工作台…</p>;
  if (error && !data) return <div className="rounded-xl border border-red-200 bg-white p-6"><h1 className="text-lg font-semibold text-red-700">ERP工作台暂时无法加载</h1><p className="mt-2 text-sm text-gray-600">{error}</p></div>;
  const production = data?.production?.data; const kit = data?.kitCheck?.data; const procurement = data?.procurement?.data; const inventory = data?.inventory?.data; const alerts = data?.alerts?.data;
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold text-gray-900">ERP工作台</h1><p className="mt-1 text-sm text-gray-500">{data?.roleView === "ADMIN" ? "全局视图" : data?.roleView === "PURCHASE" ? "采购视图" : "仓库视图"} · {data?.generatedAt ? `更新于 ${new Date(data.generatedAt).toLocaleString("zh-CN")}` : "暂无更新时间"}</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm hover:bg-gray-50"><RefreshCw className="h-4 w-4" />刷新</button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="进行中工单" value={production?.kpis?.inProgress} href="/erp/production-orders" icon={ClipboardCheck} /><Card label="即将逾期工单" value={production?.kpis?.dueSoon} href="/erp/production-orders" icon={AlertTriangle} /><Card label="库存报警" value={inventory?.alertCount} href="/erp/inventory?alertOnly=1" icon={Boxes} /><Card label="待采购物料" value={procurement?.pendingDemands} href="/erp/purchase-demands" icon={ShoppingCart} /></div><div className="grid gap-6 xl:grid-cols-2"><Section title="生产执行" error={data?.production?.error}><div className="grid grid-cols-2 gap-3 text-sm"><p>已逾期：<b>{number(production?.kpis?.overdue)}</b></p><p>待齐套：<b>{number(production?.kpis?.pendingKitCheck)}</b></p><p>缺料影响工单：<b>{number(production?.shortageOrders?.length)}</b></p><p>未来风险清单：<b>{number(production?.riskOrders?.length)}</b></p></div></Section><Section title="齐套和缺料" error={data?.kitCheck?.error}><p className="text-sm">齐套率：<b>{kit?.rate === null || kit?.rate === undefined ? "暂无数据" : `${kit.rate}%`}</b></p><p className="mt-2 text-xs text-gray-500">{kit?.formula}</p><p className="mt-3 text-sm">完全齐套 {number(kit?.sufficient)} · 缺料 {number(kit?.shortage)} · 未检查 {number(kit?.notChecked)}</p></Section><Section title="采购与供应" error={data?.procurement?.error}><p className="text-sm">延期采购明细：<b>{number(procurement?.delayedItems)}</b></p><p className="mt-2 text-sm">可见采购订单：<b>{number(procurement?.orders?.length)}</b></p><p className="mt-2 text-xs text-gray-500">仓库视图仅显示收货执行所需字段，不展示采购价格。</p></Section><Section title="库存健康" error={data?.inventory?.error}><p className="text-sm">零库存：<b>{number(inventory?.zeroCount)}</b> · 待盘点：<b>{number(inventory?.pendingChecks)}</b></p>{inventory?.inventoryValue !== undefined && <p className="mt-2 text-sm">当前库存金额：<b>¥{number(inventory.inventoryValue)}</b></p>}<p className="mt-2 text-sm">90 天无出入库：<b>{number(inventory?.staleMaterials)}</b></p></Section></div><Section title="异常与提醒" error={data?.alerts?.error}><div className="grid gap-2 text-sm sm:grid-cols-3"><p>待入库：<b>{number(alerts?.pendingStockIn)}</b></p><p>待出库：<b>{number(alerts?.pendingStockOut)}</b></p><p>最近作废：<b>{number(alerts?.recentVoids)}</b></p></div><p className="mt-3 text-xs text-gray-500">{alerts?.note}</p></Section></div>;
}
