"use client";

import { useEffect, useState } from "react";
import { DEFAULT_AUTO_DOCUMENT_RULES, DOCUMENT_NUMBER_RULES_KEY, normalizeAutoDocumentRules, type AutoDocumentRules } from "@/lib/document-number";

const labels = { PURCHASE_ORDER: "采购订单", STOCK_CHECK: "盘点单", STOCK_TRANSFER: "库存调拨单" } as const;

export default function ConfigPage() {
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const [rules, setRules] = useState<AutoDocumentRules>(DEFAULT_AUTO_DOCUMENT_RULES);
  useEffect(() => { fetch("/api/system/settings").then((res) => res.json()).then((data) => { if (!Array.isArray(data.items)) return setError(data.error || "配置加载失败"); setItems(data.items); const row=data.items.find((item:any)=>item.key===DOCUMENT_NUMBER_RULES_KEY); if(row) setRules(normalizeAutoDocumentRules(row.value)); }).catch(() => setError("配置加载失败")); }, []);
  const update = (kind: keyof AutoDocumentRules, field: string, value: string) => setRules((current) => ({ ...current, [kind]: { ...current[kind], [field]: field === "sequenceLength" ? Number(value) : value } }));
  const save = async () => { setSaving(true); setError(""); const response=await fetch("/api/system/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:DOCUMENT_NUMBER_RULES_KEY,value:rules})}); const data=await response.json(); setSaving(false); if(!response.ok)return setError(data.error||"保存失败"); setItems((current)=>[...current.filter((item)=>item.key!==DOCUMENT_NUMBER_RULES_KEY),data]); };
  return <div className="space-y-4"><div><h1 className="text-xl font-semibold">配置中心</h1><p className="text-sm text-gray-500">仅显示白名单业务配置；连接串、密码、Token、密钥和服务器控制均不会显示。</p></div>{error&&<p className="text-red-600 text-sm">{error}</p>}<section className="rounded-xl border bg-white p-4"><h2 className="font-medium">自动单据编号</h2><p className="mt-1 text-sm text-gray-500">仅可修改前缀、日期格式、流水位数、分隔符和按日重置；用户不能手工覆盖自动单号。</p><div className="mt-4 overflow-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="text-left text-gray-500"><th>单据</th><th>前缀</th><th>日期格式</th><th>流水位数</th><th>分隔符</th><th>重置周期</th></tr></thead><tbody>{(Object.keys(labels) as Array<keyof AutoDocumentRules>).map((kind)=><tr key={kind} className="border-t"><td className="py-2">{labels[kind]}</td><td><input value={rules[kind].prefix} onChange={(e)=>update(kind,"prefix",e.target.value)} className="w-20 rounded border p-1" /></td><td><input readOnly value="yyyyMMdd" className="w-24 rounded border bg-gray-50 p-1" /></td><td><input type="number" min="1" max="8" value={rules[kind].sequenceLength} onChange={(e)=>update(kind,"sequenceLength",e.target.value)} className="w-16 rounded border p-1" /></td><td><input value={rules[kind].separator} onChange={(e)=>update(kind,"separator",e.target.value)} className="w-16 rounded border p-1" /></td><td>按日</td></tr>)}</tbody></table></div><button onClick={save} disabled={saving} className="mt-4 rounded bg-gray-900 px-4 py-2 text-sm text-white disabled:opacity-50">{saving?"保存中...":"保存编号规则"}</button></section><section className="rounded-xl border bg-white p-4"><h2 className="font-medium">提醒与打印信息</h2><p className="mt-1 text-sm text-gray-500">已保存配置 {items.length} 项。</p></section></div>;
}
