import { NextRequest, NextResponse } from "next/server";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db";
import { getSessionUser, canManageInventory } from "@/lib/permissions";
import { enqueueKitRechecks } from "@/lib/kit-recheck";
import { writeOperationLog } from "@/lib/sales-items";
import { autoDocumentPrefix, DOCUMENT_NUMBER_RULES_KEY, formatAutoDocumentNo, normalizeAutoDocumentRules } from "@/lib/document-number";

export async function GET() { const user = await getSessionUser(); if (!user) return NextResponse.json({ error: "未登录" }, { status: 401 }); if (!canManageInventory(user)) return NextResponse.json({ error: "无权限" }, { status: 403 }); return NextResponse.json(await prisma.stockTransfer.findMany({ include: { items: true }, orderBy: { createdAt: "desc" } })); }
export async function POST(request: NextRequest) {
  const user = await getSessionUser(); if (!user) return NextResponse.json({ error: "未登录" }, { status: 401 }); if (!canManageInventory(user)) return NextResponse.json({ error: "无权限调拨库存" }, { status: 403 });
  const body = await request.json(); const rawItems = Array.isArray(body.items) ? body.items : [];
  if (!body.fromWarehouseId || !body.toWarehouseId || body.fromWarehouseId === body.toWarehouseId || !rawItems.length) return NextResponse.json({ error: "调出仓、调入仓和明细为必填项，且两个仓库不能相同" }, { status: 400 });
  if (new Set(rawItems.map((row:any)=>row.materialId)).size !== rawItems.length || rawItems.some((row:any)=>!row.materialId || !Number.isFinite(Number(row.quantity)) || Number(row.quantity)<=0)) return NextResponse.json({ error: "物料不能重复且数量必须大于0" }, { status: 400 });
  for(let attempt=0;attempt<3;attempt+=1) try { const result = await prisma.$transaction(async tx => {
    const warehouses = await tx.warehouse.findMany({ where: { id: { in: [body.fromWarehouseId,body.toWarehouseId] }, isActive: true } }); if (warehouses.length!==2) throw new Error("仓库不存在或已停用");
    const materialIds = rawItems.map((row:any)=>String(row.materialId)).sort();
    for (const materialId of materialIds) { await tx.$queryRaw`SELECT id FROM erp_inventories WHERE materialId=${materialId} AND warehouseId IN (${body.fromWarehouseId},${body.toWarehouseId}) ORDER BY warehouseId FOR UPDATE`; }
    const materials = await tx.material.findMany({ where: { id: { in: materialIds }, isActive: true, deletedAt: null } }); if (materials.length!==materialIds.length) throw new Error("调拨明细存在停用物料"); const materialById=new Map(materials.map(m=>[m.id,m]));
    const snapshots:any[]=[];
    for (const raw of rawItems) { const qty=new Prisma.Decimal(String(raw.quantity)); const from=await tx.inventory.findUnique({where:{warehouseId_materialId:{warehouseId:body.fromWarehouseId,materialId:raw.materialId}}}); const to=await tx.inventory.findUnique({where:{warehouseId_materialId:{warehouseId:body.toWarehouseId,materialId:raw.materialId}}}); if(!from||from.quantity.lt(qty)) throw new Error(`物料 ${materialById.get(raw.materialId)?.name||raw.materialId} 调出库存不足`); const unitCost=from.quantity.gt(0)?from.totalAmount.div(from.quantity):new Prisma.Decimal(0); const amount=unitCost.mul(qty); const fromAfter=from.quantity.sub(qty),toBefore=to?.quantity||new Prisma.Decimal(0),toAfter=new Prisma.Decimal(toBefore).add(qty); await tx.inventory.update({where:{id:from.id},data:{quantity:fromAfter,totalAmount:Prisma.Decimal.max(from.totalAmount.sub(amount),0),avgPrice:fromAfter.gt(0)?unitCost:null}}); await tx.inventory.upsert({where:{warehouseId_materialId:{warehouseId:body.toWarehouseId,materialId:raw.materialId}},create:{warehouseId:body.toWarehouseId,materialId:raw.materialId,quantity:qty,totalAmount:amount,avgPrice:unitCost},update:{quantity:toAfter,totalAmount:{increment:amount},avgPrice:unitCost}}); snapshots.push({material:materialById.get(raw.materialId)!,quantity:qty,fromBefore:from.quantity,fromAfter,toBefore,toAfter}); }
    const numberRule=normalizeAutoDocumentRules((await tx.systemSetting.findUnique({where:{key:DOCUMENT_NUMBER_RULES_KEY}}))?.value).STOCK_TRANSFER; const transferNo=formatAutoDocumentNo(numberRule,await tx.stockTransfer.count({where:{transferNo:{startsWith:autoDocumentPrefix(numberRule)}}}));
    const transfer=await tx.stockTransfer.create({data:{transferNo,fromWarehouseId:body.fromWarehouseId,toWarehouseId:body.toWarehouseId,reason:String(body.reason||"")||null,confirmedById:user.id,items:{create:snapshots.map(s=>({materialId:s.material.id,materialCodeSnapshot:s.material.code,materialNameSnapshot:s.material.name,materialSpecSnapshot:s.material.spec,unitSnapshot:s.material.unit,quantity:s.quantity,fromBeforeQty:s.fromBefore,fromAfterQty:s.fromAfter,toBeforeQty:s.toBefore,toAfterQty:s.toAfter}))}}});
    for(const s of snapshots){await tx.stockMovement.createMany({data:[{warehouseId:body.fromWarehouseId,materialId:s.material.id,type:"TRANSFER_OUT",quantity:s.quantity.neg(),beforeQty:s.fromBefore,afterQty:s.fromAfter,refType:"StockTransfer",refId:transfer.id,remark:body.reason||null,createdById:user.id},{warehouseId:body.toWarehouseId,materialId:s.material.id,type:"TRANSFER_IN",quantity:s.quantity,beforeQty:s.toBefore,afterQty:s.toAfter,refType:"StockTransfer",refId:transfer.id,remark:body.reason||null,createdById:user.id}]});}
    await enqueueKitRechecks(tx,{warehouseId:body.fromWarehouseId,materialIds,reason:`库存调拨 ${transfer.transferNo} 调出`,requestedById:user.id}); await enqueueKitRechecks(tx,{warehouseId:body.toWarehouseId,materialIds,reason:`库存调拨 ${transfer.transferNo} 调入`,requestedById:user.id}); await writeOperationLog(tx,{userId:user.id,action:"TRANSFER_INVENTORY",entityType:"StockTransfer",entityId:transfer.id,afterData:transfer}); return transfer;
  },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable}); return NextResponse.json(result,{status:201}); } catch(error:any){if((error?.code==="P2002"||error?.code==="P2034")&&attempt<2)continue;return NextResponse.json({error:(error?.code==="P2002"||error?.code==="P2034")?"调拨单编号冲突，请重试":error?.message||"调拨失败"},{status:/不足|不存在|停用/.test(error?.message||"")?400:409});}
  return NextResponse.json({error:"调拨单编号冲突，请重试"},{status:409});
}
